---
- name: webserver configuration
  hosts: dev
  tasks:
    - name: apache install
      yum:
         name:
           - httpd
           - firewalld
         state: present
    - name: apache service start
      service:
         name: httpd
         state: started
         enabled: yes
    - name: apache configure to firewall
      firewalld:
         service: http
         permanent: yes
         immediate: yes
         state: enabled
    - name: default tag
      copy:
         content: "This is MYWEB PAGE \n"
         dest: /var/www/html/index.html
